//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InduccionNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gender
    {
        public gender()
        {
            this.people = new HashSet<person>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<person> people { get; set; }
    }
}
