//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InduccionNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int identification { get; set; }
        public int age { get; set; }
        public int sex { get; set; }
    
        public virtual gender gender { get; set; }
    }
}
