//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InduccionNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int identification { get; set; }
        public int age { get; set; }
        public int sex { get; set; }
    
        public virtual gender gender { get; set; }
    }
}
